statistics/rest/urls.py
'''
Created on 28.6.2012

@author: teerytko
'''

from django.conf.urls import patterns, url
#from djangorestframework.resources import ModelResource
from rest_framework import serializers
from statistics.models import Team, League, Game, Player, Goal, Penalty
from statistics.rest.views import ListSearchModelView, MyInstanceModelView

class StatisticsBaseResource(ModelResource):
    """ Exclude only pk so that id is shown """
    exclude = ('pk')
    allow_unknown_form_fields = True


class TeamResource(StatisticsBaseResource):
    model = Team


class LeagueResource(StatisticsBaseResource):
    model = League


class GameResource(StatisticsBaseResource):
    model = Game
    include = list(StatisticsBaseResource.include) + ['home_goals', 'guest_goals']


class PlayerResource(StatisticsBaseResource):
    model = Player
    include = list(StatisticsBaseResource.include) + ['team_name', 'goals', 'assists',
                                             'penalties', 'points']

class GoalResource(StatisticsBaseResource):
    model = Goal


class PenaltyResource(StatisticsBaseResource):
    model = Penalty


urlpatterns = patterns('',
    url(r'league$', ListSearchModelView.as_view(resource=LeagueResource)),
    url(r'league/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=LeagueResource)),
    url(r'team$', ListSearchModelView.as_view(resource=TeamResource)),
    url(r'team/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=TeamResource)),
    url(r'game$', ListSearchModelView.as_view(resource=GameResource)),
    url(r'game/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=GameResource)),
    url(r'player$', ListSearchModelView.as_view(resource=PlayerResource)),
    url(r'player/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=PlayerResource)),
    url(r'goal$', ListSearchModelView.as_view(resource=GoalResource)),
    url(r'goal/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=GoalResource)),
    url(r'penalty$', ListSearchModelView.as_view(resource=PenaltyResource)),
    url(r'penalty/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=PenaltyResource)),
)
    

statistics/urls.py
'''
Created on 28.6.2012

@author: teerytko
'''

from rest_framework import routers
from statistics import views

router = routers.DefaultRouter()
router.register(r'league', views.LeagueViewSet)
router.register(r'team', views.TeamViewSet)
router.register(r'game', views.GameViewSet)
router.register(r'player', views.PlayerViewSet)
router.register(r'goal', views.GoalViewSet)
router.register(r'penalty', views.PenaltyViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

from django.conf.urls import patterns, url, include
urlpatterns = patterns('',
    url(r'^$', 'statistics.views.default'),
    url(r'^rest/', include(router.urls)),
    url(r'rest/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'(?P<league>\d+)/$', 'statistics.views.league', name='league'),
    url(r'(?P<league>\d+)/game/(?P<game>\d+)/$', 'statistics.views.game',name='game'),
    url(r'(?P<league>\d+)/team/(?P<team>\d+)/$', 'statistics.views.team', name='team'),
    url(r'(?P<league>\d+)/statistics/$', 'statistics.views.statistics', name='statistics'),
)

torpedo/urls.py
from __future__ import print_function
from cms.sitemaps import CMSSitemap
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

statistics/models.py
"""
Statistics model
"""

from datetime import timedelta
from datetime import datetime
from django.db import models
from django.contrib import admin
from django.db.models import Sum
from django.db.models import Q


class League(models.Model):
    """
    League is a set of games for a certain period of time.
    """
    name =  models.TextField()
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return "%s" % self.name


class Team(models.Model):
    """
    Team is a set of players.
    """
    name =  models.TextField(null=True, blank=True)
    league = models.ForeignKey(League, null=True, blank=True)
    #players = models.ManyToManyField('Player', related_name="teams", null=True, blank=True)

    @property
    def games(self):
        return Game.objects.filter(Q(home=self) | Q(guest=self))

    @property
    def wins(self):
        games = Game.objects.filter(Q(home=self) | Q(guest=self))
        return filter(lambda g: g.played and g.winner == self, games)

    @property
    def ties(self):
        games = Game.objects.filter(Q(home=self) | Q(guest=self))
        return filter(lambda g: g.played and g.winner == None, games)

    @property
    def lost(self):
        games = Game.objects.filter(Q(home=self) | Q(guest=self))
        return filter(lambda g: g.played and g.winner != None and g.winner != self, games)

    @property
    def points(self):
        return len(self.wins) * 2 + len(self.ties)

    @property
    def goals(self):
        return Goal.objects.filter(team=self)

    @property
    def goals_against(self):
        ga = []
        homegames = Game.objects.filter(home=self)
        for game in homegames:
            ga += game.guest_goals
        guestgames = Game.objects.filter(guest=self)
        for game in guestgames:
            ga += game.home_goals
        return ga

    @property
    def goal_difference(self):
        return self.goals.count() - len(self.goals_against)

    def __unicode__(self):
        return "Team: %r" % self.name


class Game(models.Model):
    date = models.DateTimeField()
    location = models.TextField(null=True, blank=True)
    home = models.ForeignKey(Team, related_name='home', null=True, blank=True)
    guest = models.ForeignKey(Team, related_name='guest', null=True, blank=True)
    league = models.ForeignKey(League, null=True, blank=True)

    def get_home_name(self):
        return self.home.name

    def set_home_name(self, name):
        home_team = Team.objects.get(name=name)
        self.home = home_team
    home_name = property(get_home_name, set_home_name)

    def get_guest_name(self):
        return self.guest.name

    def set_guest_name(self, name):
        guest_team = Team.objects.get(name=name)
        self.guest = guest_team
    guest_name = property(get_guest_name, set_guest_name)

    @property
    def home_goals(self):
        return Goal.objects.filter(game=self, team=self.home)

    @property
    def guest_goals(self):
        return Goal.objects.filter(game=self, team=self.guest)

    @property
    def home_players(self):
        return Player.objects.filter(team=self.home, league=self.league)

    @property
    def guest_players(self):
        return Player.objects.filter(team=self.guest, league=self.league)

    def __unicode__(self):
        return "Game: %s, %s - %s : %s - %s" % \
        (self.date, self.home,
         self.guest, self.home_goals.count(),
         self.guest_goals.count())

    @property
    def played(self):
        now = datetime.now() + timedelta(hours=3)
        gamedate = self.date.replace(tzinfo=None)
        return (now-gamedate).total_seconds() > 0

    @property
    def winner(self):
        print "Debugging winner"
        print self
        if self.home_goals.count() > self.guest_goals.count():
            return self.home
        elif self.home_goals.count() < self.guest_goals.count():
            return self.guest
        else:
            return None

class Player(models.Model):
    number = models.IntegerField(blank=True)
    name = models.TextField(blank=True)
    role= models.TextField(blank=True)
    team=models.ForeignKey(Team, blank=True, null=True)
    league = models.ForeignKey(League, null=True, blank=True)

    @property
    def team_name(self):
        #teams = self.teams.all()
        return self.team.name

    @property
    def goals(self):
        return self.scoring.count()

    @property
    def assists(self):
        return self.assisting.count()

    @property
    def points(self):
        return self.goals + self.assists

    @property
    def penalties(self):
        penalty_time = timedelta()
        for penalty in self.penalty_set.all():
            penalty_time += timedelta(hours=penalty.length.hour,
                                      minutes=penalty.length.minute,
                                      seconds=penalty.length.second,
                                      )
        return penalty_time

    def __unicode__(self):
        return "Player: #%r: %r" % (self.number, self.name)


class Goal(models.Model):
    time = models.TimeField(null=False)
    game = models.ForeignKey(Game)
    team = models.ForeignKey(Team)
    player = models.ForeignKey(Player, related_name='scoring', blank=True, null=True)
    assisting = models.ForeignKey(Player, related_name='assisting', blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    league = models.ForeignKey(League, null=True, blank=True)

    def __unicode__(self):
        return "Goal: %r, %r" % (self.player, self.time)


class Penalty(models.Model):
    time = models.TimeField(null=False)
    length = models.TimeField(null=False) 
    game = models.ForeignKey(Game)
    team = models.ForeignKey(Team)
    player = models.ForeignKey(Player, blank=True, null=True)
    reason = models.IntegerField(blank=True, null=True)
    note = models.TextField(blank=True)
    league = models.ForeignKey(League, null=True, blank=True)

    def __unicode__(self):
        return "Penalty: %r,  %r" % (self.time, self.player)

admin.site.register(League)
admin.site.register(Team)
admin.site.register(Game)
admin.site.register(Player)
admin.site.register(Goal)
admin.site.register(Penalty)

statistics/rest/views.py
from rest_framework.mixins import ListModelMixin, ModelMixin,InstanceMixin, ReadModelMixin, DeleteModelMixin
from rest_framework.views import InstanceModelView, ListOrCreateModelView, ModelView
from rest_framework.renderers import BaseRenderer
from statistics.rest.renderers import DListRenderer, DictRenderer
from django.db.models.fields import TextField, CharField
from django.db.models.fields.related import ForeignKey

from django.db.models import Q

class MyUpdateModelMixin(ModelMixin):
    """
    Behavior to update a `model` instance on PUT requests that accepts
    individual field updates
    """
    def put(self, request, *args, **kwargs):
        model = self.resource.model
        if kwargs.has_key('league'):
            kwargs.pop('league')
#             if 'league' in self._resource._model_fields_set:
#                 self.DATA['league'] = League.objects.get(id=lid)
        query_kwargs = self.get_query_kwargs(request, *args, **kwargs)

        # TODO: update on the url of a non-existing resource url doesn't work
        # correctly at the moment - will end up with a new url
        try:
            self.model_instance = self.get_instance(**query_kwargs)
            self.update = self.DATA.dict()
            self.basedata = self.DATA.dict()
            for field in self.model_instance._meta.fields:
                self.basedata.setdefault(field.name, getattr(self.model_instance, field.attname))
            self._content = self.validate_request(self.basedata, self.FILES)
            self.model_instance = self.get_instance(**query_kwargs)
            for (key, val) in self.update.items():
                if key:
                    setattr(self.model_instance, key, val)
        except model.DoesNotExist:
            self.model_instance = model(**self.get_instance_data(model, self.CONTENT, *args, **kwargs))
        self.model_instance.save()
        return self.model_instance

    @property
    def CONTENT(self):
        """
        Returns the cleaned, validated request content.

        May raise an :class:`response.ErrorResponse` with status code 400 (Bad Request).
        """
        if not hasattr(self, '_content'):
            self._content = self.validate_request(self.basedata, self.FILES)
        return self._content

class MyInstanceModelView(InstanceMixin, ReadModelMixin, MyUpdateModelMixin, DeleteModelMixin, ModelView):
    """
    A view which provides default operations for read/update/delete against a model instance.
    """
    renderers = (list(InstanceModelView.renderers) + [DListRenderer])
    _suffix = 'Instance'

    def delete(self, request, *args, **kwargs):
        """
        delete.
        """
        if kwargs.has_key('league'):
            lid = kwargs.pop('league')
            if 'league' in self._resource._model_fields_set and self.DATA is not None:
                self.DATA['league'] = lid
        super(MyInstanceModelView, self).delete(request, *args, **kwargs)

class SearchModelMixin(ListModelMixin):
    """
    Behavior to list a set of `model` instances on GET requests
    """
    def get_query_kwargs(self, request, *args, **kwargs):
        """
        """
        kwargs = request.GET.dict()
        # pop possible echo parameter
        kwargs.pop('sEcho', None)
        # If the URLconf includes a .(?P<format>\w+) pattern to match against
        # a .json, .xml suffix, then drop the 'format' kwarg before
        # constructing the query.
        if BaseRenderer._FORMAT_QUERY_PARAM in kwargs:
            del kwargs[BaseRenderer._FORMAT_QUERY_PARAM]
        return kwargs


class DataTableMixin(ListModelMixin):
    """
    List a set of `model` instances on GET requests based on
    input arguments of DataTables.
    """
    def get_ordering(self):
        return None

    def get_query(self, request, *args, **kwargs):
        """
        Create a query object for the request.

        @param sSearch: search parameter which is searched from all
        TextFields of the model.
        """
        kwargs = request.GET
        query = Q()
        sSearch = kwargs.get('sSearch')
        if sSearch is not None:
            for field in self._resource.model._meta.fields:
                if isinstance(field, TextField) or isinstance(field, CharField):
                    query |=  Q(**{'{0}__{1}'.format(field.attname, 'contains'): sSearch})
                elif isinstance(field, ForeignKey):
                    query |=  Q(**{'{0}__{1}'.format(field.name, 'name__contains'): sSearch})
        sQuery = kwargs.get('sQuery')
        if sQuery is not None:
            queryparams = {}
            for queryitem in sQuery.split(' and '):
                key, value = queryitem.split('==')
                queryparams[key] = value
            query |= Q(**queryparams)
        return query

    def get(self, request, *args, **kwargs):
        """
        Get the data for the request.
        """
        queryset = self.get_queryset()
        self.maxcount = queryset.count()
        if kwargs.has_key('league') and \
        'league' in self._resource._model_fields_set and \
        kwargs['league'] != '0':
            queryset = queryset.filter(league__id=kwargs.get('league'))
        query = self.get_query(request, *args, **kwargs)
        queryset = queryset.filter(query)
        self.totalcount = queryset.count()
        try:
            start = int(request.GET['iDisplayStart'])
            length = int(request.GET['iDisplayLength'])
            if length == -1:
                return queryset
            else:
                return queryset[start:start+length]
        except KeyError:
            return queryset


class ListSearchModelView(DataTableMixin, ListOrCreateModelView):
    """
    A view which provides default operations for searchable list, against a 
    model in the database.
    """
    renderers = (list(InstanceModelView.renderers) + [DListRenderer, DictRenderer])

    _suffix = 'List'

    def post(self, request, *args, **kwargs):
        """
        Create new.
        """
        if kwargs.has_key('league'):
            lid = kwargs.pop('league')
            if 'league' in self._resource._model_fields_set:
                self.DATA['league'] = lid
        resp = super(ListSearchModelView, self).post(request, *args, **kwargs)
        nonfields = set(self.DATA)-set(self.CONTENT)
        instance = resp.raw_content
        for key in nonfields:
            if hasattr(instance, key):
                getattr(instance, key).add(self.DATA[key])
        return resp

statistics/templates/statistics/base.html
{% extends CMS_TEMPLATE %}
{% load cms_tags %}

statistics/templates/statistics/breadcrumb.html
{% load i18n %}

<ol class="breadcrumb">
  {% for key, mainitem in breadcrumbs.items %}
    <li class="btn-group"
    {% if mainitem.children %}class="dropdown"{% endif %}>
    <a id="link-{{key}}" href="{{mainitem.href}}">{{ mainitem.name }}</a>
        {% if mainitem.children %}
        <a class="dropdown-toggle" data-toggle="dropdown" 
        href="#"><span class="caret"></span>
        </a>
        {% endif %}
        {% if mainitem.children %}
          <ul class='dropdown-menu'>
          {% for subitem in mainitem.children.values %}
            <li><a href="{{subitem.href}}">{{ subitem.name }}</a></li>
          {% endfor %}
          </ul>
        {% endif %}
    </li>
  {% endfor %}
</ol>

statistics/templates/statistics/games.html
{% extends 'statistics/base.html' %}
{% block head_datatables %}    
{% endblock %}

{% block main %}
{% include 'statistics/breadcrumb.html' %}

    {% if user.is_authenticated %}
    <button type="button" id="add-game-btn">Add game</button>
    {% endif %}
<table cellpadding="0" cellspacing="0" border="0" class="display" id="pelit">
<thead>
    <tr>
        <th width="10%">Id</th>
        <th width="20%">Aika</th>
        <th width="15%">Paikka</th>
        <th width="25%">Koti</th>
        <th width="25%">Vieras</th>
        <th width="25%">Koti maalit</th>
        <th width="25%">Vieras maalit</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td colspan="7"></td>
    </tr>
</tbody>
</table>
{% endblock %}

{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/games.view.js" type="text/javascript"></script>
{% endblock %}

statistics/templates/statistics/league.html
{% extends 'statistics/base.html' %}
{% load sekizai_tags %}

{% addtoblock "js" %}
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/league.view.js" type="text/javascript"></script>
{% endaddtoblock %}

{% block content %}
<div class="pull-left">
    <a href=".."><< Leagues</a>
</div>
<div class="pull-right">
    <a href="./statistics/">Statistics >></a>
</div>

<h2>League {{league.name}}</h2>



<div class="col-sm-12 col-md-8">
<h3>Games</h3>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Home</th>
                <th>Guest</th>
                <th>Score</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for game in games %}
        <tr class="datarow" data-id="{{ game.id }}">
            <td><a href="game/{{ game.id }}">{{ game.id }}</a></td>
            <td>{{ game.date }}</td>
            <td>{{ game.home.name }}</td>
            <td>{{ game.guest.name }}</td>
            {% if game.played %}
            <td>{{ game.home_goals.count }} - {{ game.guest_goals.count }}</td>
            {% else %}
            <td>---</td>
            {% endif %}
            <td><span style="visibility: hidden" class="glyphicon glyphicon-trash"/></td>
        </tr>
        {% endfor %}
        <tr>
        <form action="{{request.path}}" method="post">{% csrf_token %}
            <td></td>
            <td class="form-group" >
                <input id="datepicker" type="text" class="form-control" name="date" placeholder="Date">
            </td>
            <td class="form-group">
                <input type="text" class="form-control" name="home" placeholder="Home">
            </td>
            <td class="form-group">
                <input type="text" class="form-control" name="guest" placeholder="Guest">
            </td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td>
            <div class="form-group pull-right">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>                
            </td>
        </form>
        </tr>
    </tbody>
</table>
</div>

<div class="col-sm-12 col-md-4">
<h3>Teams</h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Team</th>
            </tr>
        </thead>
        <tbody>
        {% for team in teams %}
        <tr class="datarow" data-id="{{ team.id }}">
            <td><a href="team/{{ team.id }}">{{ team.id }}</a></td>
            <td>{{ team.name }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}
{% block extrajs %}
    {% addtoblock "js" %}
    <script>
    var GAMESURL="{{ request.path }}../rest/game/"
    </script>
    <script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/league.view.js" type="text/javascript"></script>
    {% endaddtoblock %}
{% endblock extrajs %}

statistics/templates/statistics/main.html
{% extends 'statistics/base.html' %}
{% load sekizai_tags %}


{% block content %}
<h2>Availables leagues</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        {% for l in leagues %}
        <tr class="datarow" data-id="{{ l.id }}">
            <td><a href="{{ l.id }}">{{ l.id }}</a></td>
            <td>{{ l.name }}</td>
            <td><span style="visibility: hidden" class="glyphicon glyphicon-trash"/></td>
        </tr>
        {% endfor %}
        <tr>
        <form id="newleague">
            {% csrf_token %}
            <td></td>
            <td class="form-group">
                <input type="text" class="form-control" id="name" placeholder="Name">
            </td>
            <td>
            <div class="form-group pull-right">
                <button type="submit" id="submit" class="btn btn-primary">Submit</button>
            </div>                
            </td>
        </form>
        </tr>
    </tbody>
</table>
{% endblock content %}

{% block extrajs %}
    {% addtoblock "js" %}
    <script>
    var POSTURL="{{ request.path }}rest/league/"
    </script>
    <script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/main.view.js" type="text/javascript"></script>
    {% endaddtoblock %}
{% endblock extrajs %}

statistics/templates/statistics/players.html
{% extends 'statistics/base.html' %}
{% block head_datatables %} 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
{% endblock %}    

{% block main %}
{% include 'statistics/breadcrumb.html' %}

<h1>Pisteet</h1>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="players">
    <thead>
        <tr>
            <th width="0%">Id</th>
            <th width="15%">Pelaaja</th>
            <th width="15%">Nimi</th>
            <th width="20%">Joukkue</th>
            <th width="5%">Maalit</th>
            <th width="5%">Syötöt</th>
            <th width="5%">Pisteet</th>
            <th width="5%">Jäähyt</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="8">null</td>
        </tr>
    </tbody>
</table>
{% endblock %}
{% block scripts %}
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/players.view.js" type="text/javascript"></script>
{% endblock %}

statistics/templates/statistics/statistics.html
{% extends 'statistics/base.html' %}
{% load sekizai_tags %}


{% block content %}
<row>
<div class="col-sm-12">
<div class="pull-left">
    <a href=".."><< League</a>
</div>
</div>
</row>
<h2>League statistics</h2>
<div class="col-md-6 col-sm-12">
<h3>Players</h3>
<table class="table table-hover" id="playerstats">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Team</th>
            <th>Goals</th>
            <th>Assists</th>
            <th>Points</th>
            <th>Penalties</th>
        </tr>
    </thead>
    <tbody>
        {% for p in players %}
        <tr>
            <td>{{ p.number }}</td>
            <td>{{ p.name }}</td>
            <td><a href="../team/{{ p.team.id }}">{{ p.team.name }}</a></td>
            <td>{{ p.goals }}</td>
            <td>{{ p.assists }}</td>
            <td>{{ p.points }}</td>
            <td>{{ p.penalties }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div id="pager" class="pager">
    <row>
    <form>
    <div class="col-sm-1">
        <span class="glyphicon glyphicon-fast-backward first"/>
    </div>
    <div class="col-sm-1">
        <span class="glyphicon glyphicon-backward prev"/>
    </div>
    <div class="col-sm-6">
        <input type="text" class="pagedisplay"/>
    </div>
    <div class="col-sm-1">
        <span class="glyphicon glyphicon-forward next"/>
    </div>
    <div class="col-sm-1">
        <span class="glyphicon glyphicon-fast-forward last"/>
    </div>
    <div class="col-sm-2">
        <select class="pagesize">
            <option selected="selected" value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
    </div>
    </form>
    </row>
</div>
</div>

<div class="col-md-6 col-sm-12">
<h3>Teams</h3>
<table class="table table-hover" id="teamstats">
    <thead>
        <tr>
            <th>Team</th>
            <th>Games</th>
            <th>W</th>
            <th>L</th>
            <th>T</th>
            <th>P</th>
            <th>G</th>
            <th>GA</th>
            <th>GD</th>
        </tr>
    </thead>
    <tbody>
        {% for t in teams %}
        <tr>
            <td><a href="../team/{{ t.id }}">{{ t.name }}</a></td>
            <td>{{ t.games.count }}</td>
            <td>{{ t.wins|length }}</td>
            <td>{{ t.lost|length }}</td>
            <td>{{ t.ties|length }}</td>
            <td>{{ t.points }}</td>
            <td>{{ t.goals.count }}</td>
            <td>{{ t.goals_against|length }}</td>
            <td>{{ t.goal_difference }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock content %}

{% block extrajs %}
    {% addtoblock "js" %}
    <script>
    var POSTURL="{{ request.path }}rest/league/"
    </script>
    <script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/statistics.view.js" type="text/javascript"></script>
    {% endaddtoblock %}
{% endblock extrajs %}

statistics/templates/statistics/teams.html
{% extends 'statistics/base.html' %}
{% block head_datatables %}
{% endblock %}


{% block main %}
{% include 'statistics/breadcrumb.html' %}

{% if perms.statistics.change_game %}
<button type="button" id="add-team-btn">Add team</button>
{% endif %}

<table class="display" id="teams">
  <thead>
    <tr>
      <th width="10%">Id</th>
      <th width="20%">Nimi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="2">null</td>
     </tr>
  </tbody>
</table>
{% endblock %}

{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/teams.view.js" type="text/javascript"></script>
{% endblock %}